[package]
name = "j2534"
version = "0.1.2"
authors = ["Altenius <jacobjm18@gmail.com>"]
keywords = ["cars", "tuning", "passthru"]
categories = ["external-ffi-bindings", "hardware-support"]
description = "PassThru (SAE J2534) bindings."
license = "MIT"
readme = "README.md"
edition = "2018"

# [badges]
# maintenance = { status = "passively-maintained" }

[dependencies]
libc = "0.2"
bitflags = "1.2"
libloading = "0.5"
winreg = "0.7"

[build-dependencies]
cc = "1.0.25"